apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: small-cluster
  region: us-east-1

nodeGroups:
  - name: ng-1
    instanceType: t4g.small
    desiredCapacity: 3
  - name: ng-2
    instanceType: t3.small
    desiredCapacity: 3
